<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-GeneralHostWithSerilog-57f23913-e164-49d4-8789-4bc09b06a549</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="serilog.json" />
  </ItemGroup>

  <ItemGroup>
    <None Include="serilog.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="6.0.1" />
  </ItemGroup>
</Project>
